/*
 * MundiAPI.Tests
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using Newtonsoft.Json.Converters;
using MundiAPI.Standard;
using MundiAPI.Standard.Utilities; 
using MundiAPI.Standard.Http.Client;
using MundiAPI.Standard.Http.Response;
using MundiAPI.Tests.Helpers;
using NUnit.Framework;
using MundiAPI.Standard;
using MundiAPI.Standard.Controllers;
using MundiAPI.Standard.Exceptions;

namespace MundiAPI.Tests
{
    [TestFixture]
    public class PlansControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests)
        /// </summary>
        private static PlansController controller;

        /// <summary>
        /// Setup test class
        /// </summary>
        [SetUp]
        public static void SetUpClass()
        {
            controller = GetClient().Plans;
        }

        /// <summary>
        /// Gets all plans 
        /// </summary>
        [Test]
        public async Task TestTestGetPlans() 
        {
            // Parameters for the API call
            int? page = null;
            int? size = null;
            string name = null;
            string status = null;
            string billingType = null;
            DateTime? createdSince = null;
            DateTime? createdUntil = null;

            // Perform API call
            Standard.Models.PlansResponse result = null;

            try
            {
                result = await controller.GetPlansAsync(page, size, name, status, billingType, createdSince, createdUntil);
            }
            catch(APIException) {};

            // Test response code
            Assert.AreEqual(200, httpCallBackHandler.Response.StatusCode,
                    "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(TestHelper.AreHeadersProperSubsetOf (
                    headers, httpCallBackHandler.Response.Headers),
                    "Headers should match");

        }

    }
}